"""reformulate init_false in item, sale and item_sale tables

Revision ID: 1ecd821c90ae
Revises: 7f53d56e144b
Create Date: 2026-07-31 15:11:29.780182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ecd821c90ae'
down_revision: Union[str, Sequence[str], None] = '7f53d56e144b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
