"""empty message

Revision ID: 29ab45b1a8ae
Revises: 72e4e0a69697
Create Date: 2026-08-02 13:50:33.997337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ab45b1a8ae'
down_revision: Union[str, Sequence[str], None] = '72e4e0a69697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_sale', sa.Column('item_id', sa.Integer(), nullable=False))
    op.add_column('item_sale', sa.Column('sale_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'item_sale', 'sales', ['sale_id'], ['id'])
    op.create_foreign_key(None, 'item_sale', 'items', ['item_id'], ['id'])
    op.drop_column('item_sale', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_sale', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'item_sale', type_='foreignkey')
    op.drop_constraint(None, 'item_sale', type_='foreignkey')
    op.drop_column('item_sale', 'sale_id')
    op.drop_column('item_sale', 'item_id')
    # ### end Alembic commands ###
