"""empty message

Revision ID: 411a296b2423
Revises: 7d2e4a6a6f6d
Create Date: 2026-08-02 18:11:52.170195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411a296b2423'
down_revision: Union[str, Sequence[str], None] = '7d2e4a6a6f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_sale', 'amount')
    op.drop_column('item_sale', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_sale', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('item_sale', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
