"""put association object pattern in sale and item tables

Revision ID: 4bb4c160b018
Revises: 411a296b2423
Create Date: 2026-08-02 21:32:08.954192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb4c160b018'
down_revision: Union[str, Sequence[str], None] = '411a296b2423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_sale', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('item_sale', sa.Column('value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_sale', 'value')
    op.drop_column('item_sale', 'amount')
    # ### end Alembic commands ###
