"""refact the relationship between item and sale

Revision ID: 5051ae921edd
Revises: a38e8d364b0d
Create Date: 2026-08-01 20:23:36.746577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5051ae921edd'
down_revision: Union[str, Sequence[str], None] = 'a38e8d364b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('item_sale_user_id_fkey'), 'item_sale', type_='foreignkey')
    op.drop_column('item_sale', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_sale', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('item_sale_user_id_fkey'), 'item_sale', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
