"""refact tables item, sale, item_sale

Revision ID: 72e4e0a69697
Revises: b800d0be8e54
Create Date: 2026-08-02 12:47:21.742381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e4e0a69697'
down_revision: Union[str, Sequence[str], None] = 'b800d0be8e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('item_sale_item_id_fkey'), 'item_sale', type_='foreignkey')
    op.drop_constraint(op.f('item_sale_sale_id_fkey'), 'item_sale', type_='foreignkey')
    op.drop_column('item_sale', 'sale_id')
    op.drop_column('item_sale', 'amount')
    op.drop_column('item_sale', 'item_id')
    op.drop_column('item_sale', 'value')
    op.add_column('sales', sa.Column('total', sa.Float(), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'total')
    op.add_column('item_sale', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('item_sale', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('item_sale', sa.Column('amount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('item_sale', sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('item_sale_sale_id_fkey'), 'item_sale', 'sales', ['sale_id'], ['id'])
    op.create_foreign_key(op.f('item_sale_item_id_fkey'), 'item_sale', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
