"""empty message

Revision ID: 7685af023e92
Revises: 974652f253b5
Create Date: 2026-08-02 13:58:50.590770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7685af023e92'
down_revision: Union[str, Sequence[str], None] = '974652f253b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_sale', sa.Column('amount', sa.Integer(), nullable=False))
    op.add_column('item_sale', sa.Column('value', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_sale', 'value')
    op.drop_column('item_sale', 'amount')
    # ### end Alembic commands ###
