"""modify itemstate enum

Revision ID: a12ffacd3fbb
Revises: bfb3e5e30804
Create Date: 2026-07-31 16:36:15.513926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a12ffacd3fbb'
down_revision: Union[str, Sequence[str], None] = 'bfb3e5e30804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
