"""put association object pattern in sale and item tables #2

Revision ID: b3a54d4fbf41
Revises: 4bb4c160b018
Create Date: 2026-08-02 21:36:14.181144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a54d4fbf41'
down_revision: Union[str, Sequence[str], None] = '4bb4c160b018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
