"""add delete on cascade for sales

Revision ID: 4064a2dbce19
Revises: b8f7821672fa
Create Date: 2026-08-11 18:57:24.041957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4064a2dbce19'
down_revision: Union[str, Sequence[str], None] = 'b8f7821672fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('item_sale_item_id_fkey'), 'item_sale', type_='foreignkey')
    op.drop_constraint(op.f('item_sale_sale_id_fkey'), 'item_sale', type_='foreignkey')
    op.create_foreign_key(None, 'item_sale', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'item_sale', 'sales', ['sale_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_sale', type_='foreignkey')
    op.drop_constraint(None, 'item_sale', type_='foreignkey')
    op.create_foreign_key(op.f('item_sale_sale_id_fkey'), 'item_sale', 'sales', ['sale_id'], ['id'])
    op.create_foreign_key(op.f('item_sale_item_id_fkey'), 'item_sale', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
